runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
  # mime_type: image/png
  # static_files: /static/(.*\.png)
  # upload: /static/(.*\.png)

- url: /.*
  script: main.app
